name: ctue_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  dio: ^5.3.2
  dartz: ^0.10.1
  data_connection_checker_tv: ^0.3.5-nullsafety
  provider: ^6.0.5
  path_provider: ^2.1.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  # rename: ^3.0.1
  syncfusion_flutter_charts: ^24.2.3
  app_settings: ^5.1.1
  carousel_slider: ^4.2.1
  audioplayers: ^5.2.1
  flutter_secure_storage: ^9.0.0
  multiple_search_selection: ^2.6.3
  flutter_dotenv: ^5.1.0
  flutter_azure_tts: ^0.1.6
  just_audio: ^0.9.36
  just_audio_mpv: any # substitute version number
  permission_handler: ^11.3.0
  audioplayers_linux: ^3.1.0
  flutter_sound:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/.env
    - assets/audios/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/games/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
    - family: DoulosSIL
      fonts:
        - asset: assets/fonts/DoulosSIL-Regular.ttf
linter:
  rules:
    - use_build_context_synchronously
